version: '3.8'
services:
  node:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - ./apps:/var/apps
    networks:
      - app_network
    links:
      - redis
    command: >
        bash -c "
          yarn --cwd /var/apps/backend
          yarn --cwd /var/apps/frontend
          /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
        "

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: edemziddah
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: jwtAuth
    volumes:
      - mongo:/data/db
    networks:
      - app_network
    command: ["mongod", "--port", "27018"]
    ports:
      - 27018:27018

  redis:
    image: redis:alpine
    ports:
      - 16379:16379
    volumes:
      - redis:/data
    networks:
      - app_network
    command: ["redis-server", "--bind", "redis", "--port", "16379"]

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    networks:
      - app_network
    ports:
      - 25:1025
      - 4000:8025
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:25

networks:
  app_network:
    driver: bridge
    
volumes:
  mongo:
  redis:
